name: nonce
description: >-
  Nonce contains a static generator that generates random alphanumeric strings,
  and can be constructed as an object containing a generated string.
version: 1.2.1
homepage: https://github.com/james-alex/nonce

environment:
  sdk: ">=2.12.0 <4.0.0"

dev_dependencies:
  pedantic: ^1.11.0
  test: ^1.16.5
